name: FasterLib
author: commandf1
description: A easy lib for developers
api-version: 1.8.8
main: space.commandf1.FasterLib.FasterLib
version: ${project.version}
website: https://github.com/PreferMC/FasterLib
load: STARTUP
database: false